# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cef4e589db58f71c2b31b7e5c75b99b9adee67e970a7faea1c7e037388f0a94798e14c352a80f3753ec5fdf87e11047848687b1e9980100147a8bd3b0d17b9ac

test:
  secret_key_base: ab2d9069af44471edbeeecf90ec70af08e2ad0078b0c1ab4455d3153c9bd95801f1ece7751e5ae21b9e8b549171890a5dfd47380e12363216db35b33b7330e3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
